language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update --profile
  - composer install --dev

script:
  - phpunit --coverage-text

matrix:
  allow_failures:
    - php: hhvm